# yamllint configuration for Helm chart linting
# See https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  colons:
    max-spaces-after: 1
    max-spaces-before: 0
    level: error
  commas:
    max-spaces-after: 1
    max-spaces-before: 0
    level: error
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    max: 3
    level: error
  hyphens:
    max-spaces-after: 1
    level: error
  indentation: disable
  key-duplicates: enable
  line-length: disable
  new-line-at-end-of-file: disable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: disable
  truthy: disable