# permissions for end users to edit kafkatopics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/managed-by: kustomize
  name: kafkatopic-editor-role
rules:
- apiGroups:
  - kafka.w6d.io
  resources:
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.w6d.io
  resources:
  - kafkatopics/status
  verbs:
  - get
