---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-operator-role
rules:
- apiGroups:
  - kafka.w6d.io
  resources:
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.w6d.io
  resources:
  - kafkatopics/finalizers
  verbs:
  - update
- apiGroups:
  - kafka.w6d.io
  resources:
  - kafkatopics/status
  verbs:
  - get
  - patch
  - update
