name: Chart Testing

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'charts/**'
      - '.github/ct.yaml'
      - '.github/lintconf.yaml'

jobs:
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history instead of just 1 commit
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the PR head

      - name: Fetch base branch
        run: git fetch origin main:main  # Ensure main branch is available

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Add chart dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add jetstack https://charts.jetstack.io
          helm repo update

      - name: Sync CRDs to chart
        run: make chart-sync-crds

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          config: .github/kind-config.yaml
          cluster_name: chart-testing

      - name: Wait for cluster ready
        run: |
          kubectl cluster-info
          kubectl wait --for=condition=Ready nodes --all --timeout=60s

      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml --debug