name: Check and build

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: make vet

      - name: Run go fmt check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -s -l .
            exit 1
          fi

      - name: Install golangci-lint
        run: make golangci-lint

      - name: Run golangci-lint
        run: make lint

      - name: Generate manifests and code
        run: |
          make manifests
          make generate

      - name: Run tests
        run: make test

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./cover.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  e2e-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up Kind
        uses: helm/kind-action@v1
        with:
          cluster_name: test-cluster
          kubectl_version: v1.31.0

      - name: Wait for cluster to be ready
        run: |
          kubectl cluster-info
          kubectl wait --for=condition=Ready nodes --all --timeout=60s

      - name: Install CRDs
        run: make install

      - name: Run e2e tests
        run: make test-e2e

  build:
    runs-on: ubuntu-latest
    needs: [test, e2e-test]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Generate manifests
        run: make manifests

      - name: Build binary
        run: make build
